### ISSUE TITLE
建议为项目提供一个网站

### ISSUE THREAD

**Issue by chenjiandongx** [jobbole/awesome-python-cn#50]
awesome-python 为其项目提供了 https://awesome-python.com/

我想是不是本项目也可以做成一个网站，使用 mkdocs，文档挂在 gh-pages 分支。

效果如下

![image](https://user-images.githubusercontent.com/19553554/40576905-2ea194e8-6130-11e8-9370-526fcec82d13.png)

![image](https://user-images.githubusercontent.com/19553554/40576907-338153e0-6130-11e8-9636-25eac28dd55f.png)

**Comment by hanxiaomax** [comment]
不错

**Comment by chenjiandongx** [comment]
我可以推送一个 PR 过来，如果你们愿意的话。

**Comment by chenjiandongx** [comment]
我和他沟通过了，他也觉得这个想法不错，只是需要拥有这个项目权限的人来开启 github pages

**Comment by xjr7670** [comment]
支持！

**Comment by hanxiaomax** [comment]
@chenjiandongx 你可以先提交pr，我可以开github pages

**Comment by chenjiandongx** [comment]
@hanxiaomax 已经 PR

**Comment by hanxiaomax** [comment]
@chenjiandongx 网站已上线，感谢

**Comment by chenjiandongx** [comment]
@hanxiaomax 🤝

**Comment by chenjiandongx** [comment]
@hanxiaomax 请问我能成为这个项目的管理员之一吗？
